"""empty message

Revision ID: 123b383ed398
Revises: 8c7cbf0f76c6
Create Date: 2021-05-25 11:46:57.649135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123b383ed398'
down_revision = '8c7cbf0f76c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('github', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=13), nullable=True))
    op.add_column('user', sa.Column('slack', sa.String(length=21), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'slack')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'github')
    op.drop_column('user', 'email')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
