"""empty message

Revision ID: 47858da645a9
Revises: 8c7cbf0f76c6
Create Date: 2021-11-10 21:25:36.724607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47858da645a9'
down_revision = '8c7cbf0f76c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('techstack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technology', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technology')
    )
    op.create_table('team_techstack',
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('techstack_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['techstack_id'], ['techstack.id'], )
    )
    op.create_table('user_techstack',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('techstack_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['techstack_id'], ['techstack.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_techstack')
    op.drop_table('team_techstack')
    op.drop_table('techstack')
    # ### end Alembic commands ###
