"""empty message

Revision ID: 4d81578a84d3
Revises: ea7204474ffa
Create Date: 2019-02-13 22:47:23.324102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d81578a84d3"
down_revision = "ea7204474ffa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jwt_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("jti", sa.String(length=36), nullable=False),
        sa.Column("token_type", sa.String(length=10), nullable=False),
        sa.Column("user_identity", sa.String(length=200), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("user", sa.Column("password", sa.String(length=100), nullable=True))
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "hashed_password",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("user", "password")
    op.drop_table("jwt_tokens")
    # ### end Alembic commands ###
