"""empty message

Revision ID: 6b3f31bc7cce
Revises: 8c7cbf0f76c6
Create Date: 2021-05-26 17:24:32.518897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6b3f31bc7cce"
down_revision = "8c7cbf0f76c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("github", sa.String(length=200), nullable=True))
    op.add_column("user", sa.Column("first_name", sa.String(length=50), nullable=True))
    op.add_column("user", sa.Column("last_name", sa.String(length=50), nullable=True))
    op.add_column("user", sa.Column("email", sa.String(length=200), nullable=True))
    op.add_column("user", sa.Column("phone", sa.String(length=13), nullable=True))
    op.add_column("user", sa.Column("slack", sa.String(length=21), nullable=True))
    op.add_column("user", sa.Column("is_admin", sa.Boolean(), nullable=True))
    op.drop_constraint("user_username_key", "user", type_="unique")
    op.create_unique_constraint(None, "user", ["github"])
    op.drop_column("user", "username")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "username", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "user", type_="unique")
    op.create_unique_constraint("user_username_key", "user", ["username"])
    op.drop_column("user", "is_admin")
    op.drop_column("user", "slack")
    op.drop_column("user", "phone")
    op.drop_column("user", "email")
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    op.drop_column("user", "github")
    # ### end Alembic commands ###
