"""Unique constraint on participant.github

Revision ID: 6ee67d4f447a
Revises: 15bee3c2078e
Create Date: 2020-02-05 16:58:59.107535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6ee67d4f447a"
down_revision = "15bee3c2078e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "participant", ["github"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "participant", type_="unique")
    # ### end Alembic commands ###
