"""empty message

Revision ID: 79060a1bab8e
Revises: 7408c872d6c0
Create Date: 2019-09-25 17:06:21.770398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "79060a1bab8e"
down_revision = "7408c872d6c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""ALTER TABLE hacknight ALTER COLUMN date TYPE DATE USING date::date""")
    op.alter_column(
        "participant",
        "email",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "participant",
        "lastname",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "participant",
        "name",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "participant",
        "phone",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=13),
        existing_nullable=True,
    )
    op.alter_column(
        "user",
        "username",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=200),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "username",
        existing_type=sa.String(length=200),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "participant",
        "phone",
        existing_type=sa.String(length=13),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "participant",
        "name",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "participant",
        "lastname",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "participant",
        "email",
        existing_type=sa.String(length=200),
        type_=sa.VARCHAR(length=30),
        existing_nullable=True,
    )
    op.alter_column(
        "hacknight",
        "date",
        existing_type=sa.Date(),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
