"""Add new table Team

Revision ID: 8c7cbf0f76c6
Revises: b3338f2ae582
Create Date: 2020-08-26 16:08:48.987798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8c7cbf0f76c6"
down_revision = "b3338f2ae582"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table(
        "team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("project_url", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_name"),
        sa.UniqueConstraint("project_url"),
    )
    op.create_table(
        "participant_team",
        sa.Column("participant_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["participant_id"], ["participant.id"],),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"],),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table("participant_team")
    op.drop_table("team")
    # ### end Alembic commands ###
