"""empty message

Revision ID: 98e8c06e83ba
Revises: 7408c872d6c0
Create Date: 2019-07-31 18:36:12.649210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e8c06e83ba'
down_revision = '7408c872d6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('participant', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.drop_column('participant', 'name')
    op.drop_column('participant', 'lastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('lastname', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('participant', sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('participant', 'last_name')
    op.drop_column('participant', 'first_name')
    # ### end Alembic commands ###
