"""empty message

Revision ID: 9aa6f9eb68b7
Revises: 8c7cbf0f76c6
Create Date: 2021-07-14 17:07:23.310942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9aa6f9eb68b7"
down_revision = "8c7cbf0f76c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "participant",
        sa.Column("github_username", sa.String(length=200), nullable=False),
    )
    op.drop_constraint("participant_github_key", "participant", type_="unique")
    op.create_unique_constraint(None, "participant", ["github_username"])
    op.drop_column("participant", "github")
    op.add_column(
        "user", sa.Column("github_username", sa.String(length=200), nullable=True)
    )
    op.drop_constraint("user_github_key", "user", type_="unique")
    op.create_unique_constraint(None, "user", ["github_username"])
    op.drop_column("user", "github")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("github", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "user", type_="unique")
    op.create_unique_constraint("user_github_key", "user", ["github"])
    op.drop_column("user", "github_username")
    op.add_column(
        "participant",
        sa.Column(
            "github", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "participant", type_="unique")
    op.create_unique_constraint("participant_github_key", "participant", ["github"])
    op.drop_column("participant", "github_username")
    # ### end Alembic commands ###
