"""empty message

Revision ID: c3ffa4d96114
Revises: 22771e69d10c
Create Date: 2021-07-21 18:56:57.879154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3ffa4d96114"
down_revision = "22771e69d10c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "participant",
        sa.Column("github_username", sa.String(length=200), nullable=False),
    )
    op.create_unique_constraint(None, "participant", ["github_username"])
    op.drop_column("participant", "github")
    op.alter_column(
        "user", "github_username", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "github_username", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    op.add_column(
        "participant",
        sa.Column(
            "github", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "participant", type_="unique")
    op.drop_column("participant", "github_username")
    # ### end Alembic commands ###
