"""empty message

Revision ID: e77f6676bf8a
Revises: 79060a1bab8e
Create Date: 2019-10-02 16:44:31.306623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77f6676bf8a'
down_revision = '79060a1bab8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('participant', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.drop_column('participant', 'lastname')
    op.drop_column('participant', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('participant', sa.Column('lastname', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('participant', 'last_name')
    op.drop_column('participant', 'first_name')
    # ### end Alembic commands ###
