"""empty message

Revision ID: e77f6676bf8a
Revises: 79060a1bab8e
Create Date: 2019-10-02 16:44:31.306623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e77f6676bf8a"
down_revision = "79060a1bab8e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("participant", "name", new_column_name="first_name")
    op.alter_column("participant", "lastname", new_column_name="last_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("participant", "first_name", new_column_name="name")
    op.alter_column("participant", "last_name", new_column_name="lastname")
    # ### end Alembic commands ###
