name: deploy


on:
  workflow_call:
    inputs:
      environment-name:
        required: true
        type: string
      environment-url:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-resource-name:
        required: true
      aws-cloudfront-id:
        required: true


jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment-name }}
      url: ${{ inputs.environment-url }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}

      - uses: CodeForPoznan/actions/deploy-frontend@v1
        with:
          aws-resource-name: ${{ secrets.aws-resource-name }}
          aws-cloudfront-id: ${{ secrets.aws-cloudfront-id }}

      - uses: CodeForPoznan/actions/deploy-backend@v1
        with:
          aws-resource-name: ${{ secrets.aws-resource-name }}
          aws-cloudfront-id: ${{ secrets.aws-cloudfront-id }}

