name: frontend


on:
  workflow_call:
  pull_request:
    branches: [master]
    paths: ['frontend/**']


jobs:
  frontend:
    name: lint and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v2
      - uses: CodeForPoznan/actions/setup-frontend@v1

      - run: yarn run lint
      - run: yarn run test

      - uses: CodeForPoznan/actions/pack-frontend@v1
        if: github.event_name != 'pull_request'

