name: PR linter

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CodeForPoznan/actions/setup-backend@v2
      - uses: CodeForPoznan/actions/lint-backend@v2
