name: PR linter

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: CodeForPoznan/actions/setup-backend@main
        with:
          python-version: 3.8

      - uses: CodeForPoznan/actions/lint-backend@main
