name: production


on:
  workflow_dispatch:
  release:
    types: [released]


jobs:
  frontend:
    uses: ./.github/workflows/frontend.yml

  backend:
    uses: ./.github/workflows/backend.yml

  production:
    uses: ./.github/workflows/deploy.yml
    needs: [frontend, backend]
    with:
      environment-name: production
      environment-url: https://codeforpoznan.pl
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-resource-name: ${{ secrets.AWS_RESOURCE_NAME }}
      aws-cloudfront-id: ${{ secrets.AWS_CLOUDFRONT_ID }}

