name: staging


on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['frontend/**', 'backend/**']


jobs:
  frontend:
    uses: ./.github/workflows/frontend.yml

  backend:
    uses: ./.github/workflows/backend.yml

  staging:
    uses: ./.github/workflows/deploy.yml
    needs: [frontend, backend]
    with:
      environment-name: staging
      environment-url: https://dev.codeforpoznan.pl
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-resource-name: ${{ secrets.AWS_RESOURCE_NAME }}
      aws-cloudfront-id: ${{ secrets.AWS_CLOUDFRONT_ID }}

