name: test frontend

on:
  workflow_call:
  pull_request:
    branches: [master]
    paths: ['frontend/**']

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3
      - uses: CodeForPoznan/actions/setup-frontend@v2

      - run: yarn run lint
      - run: yarn run test

      - uses: CodeForPoznan/actions/pack-frontend@v2
        if: github.event_name != 'pull_request'

